### ISSUE TITLE
Product import fails if file is missing in Sylius

### ISSUE THREAD

**Issue by zappzarapp** [sulu/SuluSyliusConsumerBundle#42]
I had the problem that there was a `product_image` in the Sylius database but the related file was missing in the file system. 

That lead to a fatal error when trying to consume the message queue and no possibilty to continue/skip the failing  item. I know that (in the first place) this should not happen in Sylius but it would also be good if in this case the import into Sulu would skip this file, and maybe just log that it wasn't able to fetch the file. 

```
11:05:22 DEBUG     [doctrine] INSERT INTO me_file_version_meta (title, description, copyright, credits, locale, idFileVersions) VALUES (?, ?, ?, ?, ?, ?)
[
  1 => "Capocorda tubolare 50mm2/M10",
  2 => "",
  3 => null,
  4 => null,
  5 => "it",
  6 => 34
]
PHP Fatal error:  require(): Failed opening required '/Users/matthiasproksch/projects/steffen-shop/steffen-sulu/vendor/composer/../symfony/debug/Exception/SilencedErrorContext.php' (include_path='.:/usr/local/Cellar/php/7.2.12_2/share/php/pear') in /Users/matthiasproksch/projects/steffen-shop/steffen-sulu/vendor/symfony/debug/DebugClassLoader.php on line 143
PHP Stack trace:
```

**Comment by zappzarapp** [comment]
The error message above is wrong, this is the correct one which we got today:

```[2018-12-17 14:06:48] messenger.WARNING: An exception occurred while handling message Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\SynchronizeProductMessage {"message":"[object] (Sulu\\Bundle\\SyliusConsumerBundle\\Model\\Product\\Message\\SynchronizeProductMessage: {})","class":"Sulu\\Bundle\\SyliusConsumerBundle\\Model\\Product\\Message\\SynchronizeProductMessage","exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 404): Client error: `GET https://www.mydomain.at/media/image/7d/d1/3c46942bd9f0cd381e170ed38c39.png` resulted in a `404 Not Found` response:\n<!DOCTYPE html>\n\n<html lang=\"de\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=e (truncated...)\n at /var/www/steffen/staging/releases/64/steffen-sulu/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)"} []
```
The processor was stuck at a few thousand entries and wasn't able to process the rest of the queue.

**Comment by trickreich** [comment]
Fixed with https://github.com/sulu/SuluSyliusConsumerBundle/pull/63
